### PR TITLE
A/B 测试框架

### PR DESCRIPTION
**Pull request by WuLC**
Google 一篇关于 A/B 测试框架的论文，涉及到如何切分流量以同时进行多个 A/B 测试，工程性很强

### CODE REVIEW

**Comment by WuLC** [comment]
删掉了 CTR 相关的东西，原想提两个 PR 的，但是会混在一起

**Comment by wzhe06** [comment]
The paper is useful and solid. But could you rebase the master branch firstly? It seems too many commits.Thanks.

**Comment by WuLC** [comment]
Sorry，already fixed

**Comment by wzhe06** [comment]
Thanks for continuous contribution!

**Comment by WuLC** [comment]
No thanks, I also benefit a lot from this repository

**Pull request merged**
